title:  # your name (or website title) here
logo: "/images/ArielHarris.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  As a recent graduated with a Master's degree in Data Science from the University of Denver, I am currently searching for opportunities to work in data science or analytics. 
  <br><br>
  My background was first in Electrical and Computer Engineering, which I studied for my undergrad. However during my senior capstone project, I discovered that playing with data is where my true interests lie. I decided to follow this passion to graduate school and pursue my MS. Through my time earning my degree I found I also enjoy interpreting and relaying data driven insights into concise and understandable stories, otherwise: translating data science results into stories and visualizations that can be understood by all.
  <br><br>
  <a href="https://www.linkedin.com/in/ariel-harris-892964138/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
